# DRAFT:
# XP_PER_BOTTLE: int
# LOGMODE: int
# SOUND: boolean
# SUCESS-MESSAGE: boolean
# BLOCK-NO-PERM-MESSAGE: boolean
# RANDOM-MODE: int (Range +/- int, 0 = off)
# MESSAGES:
#   No Permission
#   Success
#   OwnXP
#   ForeignXP
#   NotEnough
#   Inventory Full
#   Help
#   Player not found